### ISSUE TITLE
知乎更换了登陆接口

### ISSUE THREAD

**Issue by JNULYD** [liyaopinner/ArticleSpider-resourses#1]
老师厉害，都给破解了

**Comment by xianfuxing** [comment]
知乎的我已经参考网上教程，改造为scrapy登录了

**Comment by chaozai1028l** [comment]
老师知乎最新的scrapy登录怎么写，求助

**Comment by einsli** [comment]
> 老师知乎最新的scrapy登录怎么写，求助

老哥这个问题你解决了吗？

**Comment by JNULYD** [comment]
已经解决，使用selenium获取cookie可以解决。网站防爬升级太快了。
